# Generated by Django 5.0.4 on 2024-04-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_diabetestype_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='diabetesType',
            field=models.CharField(blank=True, choices=[('type 1', 'Type 1'), ('type 2', 'Type 2'), ('pre-diabetes', 'Prediabetes'), ('gestational', 'Gestational'), ('none', 'None')], max_length=20),
        ),
    ]
