# Generated by Django 5.0.4 on 2024-04-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_diabetestype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='diagnosed_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dietary_preference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
